### ISSUE TITLE
Bucket not found error

### ISSUE THREAD

**Issue by mattj23** [mattj23/MysqlBackupAgent#1]
Happens on first run on new minio source

```
backups: Minio.Exceptions.BucketNotFoundException: MinIO API responded with message=Not found.
   at Minio.MinioClient.ParseErrorFromContent(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 570
   at Minio.MinioClient.ParseError(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 431
   at Minio.MinioClient.<>c.<.ctor>b__84_0(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 83
   at Minio.MinioClient.HandleIfErrorResponse(IRestResponse response, IEnumerable`1 handlers, DateTime startTime) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 605
   at Minio.MinioClient.ExecuteTaskCoreAsync(IEnumerable`1 errorHandlers, IRestRequest request, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 405
   at Minio.BucketRegionCache.Update(MinioClient client, String bucketName) in /q/.q/sources/minio-dotnet/Minio/BucketRegionCache.cs:line 104
   at Minio.MinioClient.GetRegion(String bucketName) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 134
   at Minio.MinioClient.CreateRequest(Method method, String bucketName, String objectName, Dictionary`2 headerMap, String contentType, Object body, String resourcePath) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 167
   at Minio.MinioClient.GetObjectListAsync(String bucketName, String prefix, String delimiter, String marker, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/BucketOperations.cs:line 236
   at Minio.MinioClient.<>c__DisplayClass4_0.<<ListObjectsAsync>b__0>d.MoveNext() in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/BucketOperations.cs:line 167
--- End of stack trace from previous location where exception was thrown ---
   at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception) in /_/Rx.NET/Source/src/System.Reactive/Internal/ExceptionServicesImpl.cs:line 16
   at System.Reactive.ExceptionHelpers.ThrowIfNotNull(Exception exception) in /_/Rx.NET/Source/src/System.Reactive/Internal/ExceptionServices.cs:line 22
   at System.Reactive.Subjects.AsyncSubject`1.GetResult() in /_/Rx.NET/Source/src/System.Reactive/Subjects/AsyncSubject.cs:line 439
   at MySqlBackupAgent.Services.MinioFileService.GetExistingFiles() in /app/MySqlBackupAgent/Services/MinioFileService.cs:line 52
   at MySqlBackupAgent.Models.DbBackupTarget.PerformBackup() in /app/MySqlBackupAgent/Models/DbBackupTarget.cs:line 191
   at MySqlBackupAgent.Models.DbBackupTarget.PerformBackup() in /app/MySqlBackupAgent/Models/DbBackupTarget.cs:line 242
   at MySqlBackupAgent.Models.DbBackupTarget.RunJob() in /app/MySqlBackupAgent/Models/DbBackupTarget.cs:line 141
```

**Comment by mattj23** [comment]
Fixed with 00b8bd2f89f19045ab4a039cfc402b5d2ca6492b
